In [5]:
import numpy as np
mi_array = np.array([1,2,3,4,5])
print(mi_array)

[1 2 3 4 5]


In [6]:

#suma de matriz
import numpy as np
array1= np.array([1,2,3])
array2= np.array([4,5,6])
resultado= array1+array2
print(resultado)

[5 7 9]


In [7]:
#Multiplicacion de matriz
import numpy as np
array1= np.array([1,2,3])
array2= np.array([4,5,6])
resultado= array1*array2
print(resultado)

[ 4 10 18]


In [8]:
#Traspuesta de matriz (filas se convierten en columnas)
matriz = np.array([[1,2],[3,4]])
matriz_traspuesta = matriz.T
print(matriz_traspuesta)

[[1 3]
 [2 4]]


In [9]:
#Matriz con numpy y sin numpy
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)
#sin numpy (listas anidadas)
matriz2 = [[1,2,3],[4,5,6],[7,8,9]]
for fila in matriz2:
    for elemento in fila:
        print(elemento, end=',')
    print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1,2,3,
4,5,6,
7,8,9,


In [10]:
#multiplicacion con numpy y sin numpy
import numpy as np
A = np.array([[6,4],[3,2]])
B = np.array([[6,4],[3,2]])
resultado = np.dot(A,B)
print("resultado")
print(resultado)
#sin numpy


resultado
[[48 32]
 [24 16]]


In [11]:
A = [[6,4],[3,2]]
B = [[6,4],[3,2]]
resultado = [[0,0],[0,0]]
for i in range(2):
    for j in range(2):
        for k in range(2):
            resultado[i][j] += A[i][k] * B[k][j]
print("Resultado de la multiplicación:")
for fila in resultado:
    print(fila)


Resultado de la multiplicación:
[48, 32]
[24, 16]


In [2]:
import pandas as pd
serie = pd.Series([1,2,3])
print(serie)
items = {'a':1,'b':2,'c':3}
pd.Series(items)
pd.Series([1,2,3],name='integers')

0    1
1    2
2    3
dtype: int64


0    1
1    2
2    3
Name: integers, dtype: int64

In [2]:
import pandas as pd
import string
valores_enteros = list(range(1,27))
etiquetas = list(string.ascii_uppercase)
serie = pd.DataFrame({'valor':valores_enteros},index=etiquetas)
print(serie)

   valor
A      1
B      2
C      3
D      4
E      5
F      6
G      7
H      8
I      9
J     10
K     11
L     12
M     13
N     14
O     15
P     16
Q     17
R     18
S     19
T     20
U     21
V     22
W     23
X     24
Y     25
Z     26


In [3]:
data = {'Apple': 147000,
'Samsung': 267937,
'Google': 135301,
'Microsoft': 163000,
'Huawei': 197000,
'Dell': 158000,
'Facebook': 58604,
'Foxconn': 878429,
'Sony': 109700}
employees = pd. Series(data, name='Tech Employees')
employees.index

Index(['Apple', 'Samsung', 'Google', 'Microsoft', 'Huawei', 'Dell', 'Facebook',
       'Foxconn', 'Sony'],
      dtype='object')

In [4]:
data = {'Apple': 147000,
'Samsung': 267937,
'Google': 135301,
'Microsoft': 163000,
'Huawei': 197000,
'Dell': 158000,
'Facebook': 58604,
'Foxconn': 878429,
'Sony': 109700}
employees = pd. Series(data, name='Tech Employees')
employees.values

array([147000, 267937, 135301, 163000, 197000, 158000,  58604, 878429,
       109700])

In [16]:
data = {'Apple': 147000,
'Samsung': 267937,
'Google': 135301,
'Microsoft': 163000,
'Huawei': 197000,
'Dell': 158000,
'Facebook': 58604,
'Foxconn': 878429,
'Sony': 109700}
employees = pd. Series(data, name='Tech Employees')
print(employees)

Apple        147000
Samsung      267937
Google       135301
Microsoft    163000
Huawei       197000
Dell         158000
Facebook      58604
Foxconn      878429
Sony         109700
Name: Tech Employees, dtype: int64


In [5]:
employees.dtype

dtype('int64')

In [14]:
employees.name

'Tech Employees'

In [17]:
employees.iloc[0]

147000

In [15]:
employees [-1]

/var/folders/03/fv0q_y693gq6wh4vl8097rqh0000gn/T/ipykernel_968/1411036553.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  employees [-1]


109700

In [9]:
employees.iloc[1:6:2]

Samsung      267937
Microsoft    163000
Dell         158000
Name: Tech Employees, dtype: int64

In [10]:
employees.iloc[2:5]

Google       135301
Microsoft    163000
Huawei       197000
Name: Tech Employees, dtype: int64

In [11]:
employees['Apple']

147000

In [12]:
employees['Apple':'Huawei']

Apple        147000
Samsung      267937
Google       135301
Microsoft    163000
Huawei       197000
Name: Tech Employees, dtype: int64

In [13]:
employees['Apple':'Huawei':2]

Apple     147000
Google    135301
Huawei    197000
Name: Tech Employees, dtype: int64

In [18]:
employees.head(3)

Apple      147000
Samsung    267937
Google     135301
Name: Tech Employees, dtype: int64

In [19]:
employees.tail(3)

Facebook     58604
Foxconn     878429
Sony        109700
Name: Tech Employees, dtype: int64

In [20]:
employees > 200_000

Apple        False
Samsung       True
Google       False
Microsoft    False
Huawei       False
Dell         False
Facebook     False
Foxconn       True
Sony         False
Name: Tech Employees, dtype: bool

In [25]:
employees[employees > 200_000]

Samsung    267937
Foxconn    878429
Name: Tech Employees, dtype: int64

In [22]:
#Ordenammiento por valores
employees.sort_values()

Facebook      58604
Sony         109700
Google       135301
Apple        147000
Dell         158000
Microsoft    163000
Huawei       197000
Samsung      267937
Foxconn      878429
Name: Tech Employees, dtype: int64

In [23]:
#Ordenamiento por indice
employees.sort_index()

Apple        147000
Dell         158000
Facebook      58604
Foxconn      878429
Google       135301
Huawei       197000
Microsoft    163000
Samsung      267937
Sony         109700
Name: Tech Employees, dtype: int64

In [28]:
#Diccionario de listas
datafr = {'A':[1,2,3],'B':[4,5,6]}
pd.DataFrame(datafr)

A  B
0  1  4
1  2  5
2  3  6

In [3]:
#Lista de diccionarios
data2 = [{'A':1,'B':2,'C':3},{'A':4,'B':5,'C':6}]
pd.DataFrame(data2)

A  B  C
0  1  2  3
1  4  5  6

In [8]:
data = {'Apple': 147000,
'Samsung': 267937,
'Google': 135301,
'Microsoft': 163000,
'Huawei': 197000,
'Dell': 158000,
'Facebook': 58604,
'Foxconn': 878429,
'Sony': 109700}
employees = pd. Series(data, name='Tech Employees')
data2 = {'Apple': 12200,
'Samsung': 26765,
'Google': 129987,
'Microsoft': 124222,
'Huawei': 435452,
'Dell': 323445,
'Facebook': 2345,
'Foxconn': 333323,
'Sony': 123423}
Revenues = pd. Series(data2, name='Tech Revenues')
pd.DataFrame({'employees':employees,'Revenues':Revenues})

employees  Revenues
Apple         147000     12200
Samsung       267937     26765
Google        135301    129987
Microsoft     163000    124222
Huawei        197000    435452
Dell          158000    323445
Facebook       58604      2345
Foxconn       878429    333323
Sony          109700    123423

In [11]:
# Crear un diccionario de Listas donde cada Lista representa una columna
data = {
'Island': ['Gran Canaria', 'Tenerife', 'La Palma', 'Lanzarote', 'La Gomera', 'El hierro', 'Fuerteventura'],
'Population': [855521, 928604, 83458, 155812,21678,11147,119732],
'Area': [1560.1, 2034.38,708.32, 845.94,369.76,278.71,1659],
'Province': ['LPGC', 'SCTF', 'SCTF' , 'LPGC', 'SCTF', 'SCTF' , 'LPGC']
}
# Crear el DataFrame
df = pd.DataFrame(data)
# Mostrar el DataFrame
print(df)

          Island  Population     Area Province
0   Gran Canaria      855521  1560.10     LPGC
1       Tenerife      928604  2034.38     SCTF
2       La Palma       83458   708.32     SCTF
3      Lanzarote      155812   845.94     LPGC
4      La Gomera       21678   369.76     SCTF
5      El hierro       11147   278.71     SCTF
6  Fuerteventura      119732  1659.00     LPGC


In [13]:
# Crear una Lista de Listas donde cada Lista representa una fila
data = [
['Gran Canaria', 855521, 1560.1, 'LPGC'],
['Tenerife', 344553, 34654.1, 'SCTF'],
['La palma', 424532, 2344.4, 'SCTF'],
['Lanzarote', 776654, 0984.1, 'LPGC'],
['La Gomera', 235456, 2344.5, 'SCTF'],
['El hierro', 546676, 6543.1, 'CSTF'],
['Fuerteventura', 119732, 1659, 'LPGC']]
# Definir Los nombres de las columnas
column_names = ['Island', 'Population', 'Area', 'Province']
# Crear el DataFrame
df = pd.DataFrame(data, columns=column_names)
# Mostrar el DataFrame
print(df)

          Island  Population     Area Province
0   Gran Canaria      855521   1560.1     LPGC
1       Tenerife      344553  34654.1     SCTF
2       La palma      424532   2344.4     SCTF
3      Lanzarote      776654    984.1     LPGC
4      La Gomera      235456   2344.5     SCTF
5      El hierro      546676   6543.1     CSTF
6  Fuerteventura      119732   1659.0     LPGC


In [21]:
#INDICE
stats = pd.DataFrame({'A':[1,2],'B':[3,4]})
stats.set_index('A')

B
A   
1  3
2  4

In [26]:
pd.DataFrame({'A':[1,2],'B':[3,4]}, index=['R1','R2'])

A  B
R1  1  3
R2  2  4

In [30]:
pd.DataFrame({'A':[1,2],'B':[3,4]}, index=['R1','R2']).reset_index()

index  A  B
0    R1  1  3
1    R2  2  4

In [32]:
# Crear un diccionario de Listas donde cada Lista representa una columna
democan = {
'Island': ['Gran Canaria', 'Tenerife', 'La Palma', 'Lanzarote', 'La Gomera', 'El hierro', 'Fuerteventura'],
'Population': [855521, 928604, 83458, 155812,21678,11147,119732],
'Area': [1560.1, 2034.38,708.32, 845.94,369.76,278.71,1659],
'Province': ['LPGC', 'SCTF', 'SCTF' , 'LPGC', 'SCTF', 'SCTF' , 'LPGC']
}
# Crear el DataFrame
df = pd.DataFrame(democan)
df.set_index('Island')

Population     Area Province
Island                                     
Gran Canaria       855521  1560.10     LPGC
Tenerife           928604  2034.38     SCTF
La Palma            83458   708.32     SCTF
Lanzarote          155812   845.94     LPGC
La Gomera           21678   369.76     SCTF
El hierro           11147   278.71     SCTF
Fuerteventura      119732  1659.00     LPGC

In [36]:
#Lectura de fuentes externas
df = pd.read_csv('car-data.csv')

In [38]:
#Primeros 5 registros
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [39]:
#Ultimos cinco registros
df.tail(5)

Make   Model  Year                Engine Fuel Type  Engine HP  \
11909    Acura     ZDX  2012     premium unleaded (required)      300.0   
11910    Acura     ZDX  2012     premium unleaded (required)      300.0   
11911    Acura     ZDX  2012     premium unleaded (required)      300.0   
11912    Acura     ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln  Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                  Market Category Vehicle Size  Vehicle Style  highway MPG  \
11909  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11910  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11911  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11912  Crossover,Hatchback,Luxury      Midsize  4dr Hatchback           23   
11913                      Luxury      Midsize          Sedan           26   

       city mpg  Popularity   MSRP  
11909        16         204  46120  
11910        16         204  56670  
11911        16         204  50620  
11912        16         204  50920  
11913        17          61  28995

In [40]:
df.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06